---

- name: Tuning sysctl
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { key: net.core.somaxconn, value: 65536 }
    - { key: net.ipv4.tcp_max_tw_buckets, value: 1440000 }
    - { key: net.ipv4.ip_local_port_range, value: "1024 65535" }
    - { key: net.ipv4.tcp_fin_timeout, value: 15 }
    - { key: net.ipv4.tcp_window_scaling, value: 1 }
    - { key: net.ipv4.tcp_max_syn_backlog, value: 3240000 }

