---

- name: Tuning sysctl
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { key: net.ipv4.tcp_max_syn_backlog, value: 100000 }
    - { key: net.core.somaxconn, value: 100000 }
    - { key: net.core.netdev_max_backlog, value: 100000 }
    - { key: net.ipv4.ip_local_port_range, value: "1024 65535" }

