---

# Installation and configuration of nginx

- hosts: nginx
  user: "{{ nginx_instance_user }}"
  become: yes
  become_method: sudo
  connection: ssh
  pre_tasks:
    - name: Fail if OS is not Centos 6
      fail:
        msg: "The playbook only supports Centos 6"
      when: "ansible_distribution != 'CentOS' and ansible_distribution_major_version != '6'"

  roles:
     - { role: nginx, when: "ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'" }
