---


- name: Copy Timestamp application
  template:
    src: ts_app.js.j2
    dest: "/home/{{ app_user }}/ts_app.js"

- name: Install pm2
  npm:
    name: pm2
    global: yes
    state: present

- name: add systemv to pm2 startup
  command: "pm2 startup systemv"

- name: delete existing pm2 processes if running
  command: "pm2 delete {{ server_id }}"
  ignore_errors: yes

- name: start pm2 process
  command: 'pm2 start --name "{{ server_id }}" ts_app.js'
 
- name: save pm2
  command: "pm2 save" 
